### ISSUE TITLE
Is the short url gone forever?

### ISSUE THREAD

**Issue by oddlama** [eoli3n/archiso-zfs#12]
Thanks for this awesome script.

Is there any specific reason why your removed the short url `https://eoli3n.github.io/archzfs/init`?
I must admit Ive become quite a fan of the short URL as it is so easy to remember and type, so naturally I'm sad to see it go.

If so, I'd update my scripts to point to the new one.

**Comment by eoli3n** [comment]
> Thanks for this awesome script.

You're welcome

> Is there any specific reason why your removed the short url https://eoli3n.github.io/archzfs/init?

Yes, it ensures that the script you use is the same as the github one (because it is directly that one).
Using ``curl | bash`` is not safe by design, if you don't read the script. Using a different source than the *real* one on github is worse.
The one on the short url was a submodule on my blog, which needed an update at each new commit on the main project, which is not necessary.

The new one is a bit longer, but more safe, and have the benefit to be able to download another branch for tests etc.

See https://github.com/eoli3n/archiso-zfs/commit/4d726eafbb0640a45af8b56bd73659b7296a3092

> If so, I'd update my scripts to point to the new one.

Please yes, sorry for the inconvenience.
